name: webfeed_advanced
version: 0.0.2
description: webfeed_advance is a dart package for parsing RSS and Atom feeds. Media, DublinCore, iTunes, Syndication, Podcast and Custom namespaces are also supported.
homepage: https://github.com/sadreactonly/webfeed_advance
environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  xml: ^6.3.0
  intl: ^0.18.1
dev_dependencies:
  test: ^1.3.0
  http: "^0.13.0"
